language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
after_success:
  - './.travis/travis-doc-upload.sh'
script:
  # only build with default features
  - cargo build --verbose
  # build and test with all features
  - cargo test --verbose --all-features
